---
- name: Create SSH restricted Linux User
  hosts: all
  become: true
  become_user: root
  tasks: 
    - name: Ensure ssh-users group is created
      group: 
        name: ssh-users
        gid: 3000
        state: present
      notify: 
        - Restrict SSH in SSHD Config
        - Restart sshd service
        
    - name: Create SSH Denied user
      user:
        name: "{{ user }}"
        comment: "Some User"
        uid: "{{ uid }}"
        password: "ssh-my-pass-secret"
        home: /home/"{{ user }}"
        shell: /bin/bash

    - name: Allow SSH Access
      user:
        name: "{{ user }}"
        group: ssh-users
        append: yes
      when: remote_login == "True"

  handlers:
    - name: Restrict SSH in SSHD Config
      lineinfile:
        path: /etc/ssh/sshd_config
        line: AllowGroups ssh-users
        state: present
      
    - name: Restart sshd service
      service: 
        name: sshd
        state: restarted
